// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVRHqJCOsEO0CNY9YpqOxjiFi9jDEo2Lc',
    appId: '1:187999537845:web:3e400a75ee0105085a4cfc',
    messagingSenderId: '187999537845',
    projectId: 'fir-push-77e82',
    authDomain: 'fir-push-77e82.firebaseapp.com',
    storageBucket: 'fir-push-77e82.appspot.com',
    measurementId: 'G-C8LWFQBM8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAruKGkLMt43r4PGh_xxKy9LsqGp9Su8pY',
    appId: '1:187999537845:android:4221efa1488315935a4cfc',
    messagingSenderId: '187999537845',
    projectId: 'fir-push-77e82',
    storageBucket: 'fir-push-77e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKJVgZEZlrTttknSizycBVY8fM0ZtcCaA',
    appId: '1:187999537845:ios:cb35b360ba9460725a4cfc',
    messagingSenderId: '187999537845',
    projectId: 'fir-push-77e82',
    storageBucket: 'fir-push-77e82.appspot.com',
    iosBundleId: 'com.example.firebasePush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKJVgZEZlrTttknSizycBVY8fM0ZtcCaA',
    appId: '1:187999537845:ios:cb35b360ba9460725a4cfc',
    messagingSenderId: '187999537845',
    projectId: 'fir-push-77e82',
    storageBucket: 'fir-push-77e82.appspot.com',
    iosBundleId: 'com.example.firebasePush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVRHqJCOsEO0CNY9YpqOxjiFi9jDEo2Lc',
    appId: '1:187999537845:web:a34a184b9efdeea05a4cfc',
    messagingSenderId: '187999537845',
    projectId: 'fir-push-77e82',
    authDomain: 'fir-push-77e82.firebaseapp.com',
    storageBucket: 'fir-push-77e82.appspot.com',
    measurementId: 'G-LWWF6VCRKV',
  );
}
